version: '3.7'

# Suggested deployment command:
#   docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c docker-registry.yaml docker
# All services, networks, etc. will then get an "docker_" prefix,
# eg. "docker_registry"

services:
  registry:
    deploy:
      placement:
        constraints:
          - node.labels.role==infrastructure
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_reverse-proxy"

        - "traefik.http.routers.docker_registry.entrypoints=websecure"
        - "traefik.http.routers.docker_registry.tls=true"
        - "traefik.http.routers.docker_registry.rule=Host(`build-docker.couchbase.com`)"
        - "traefik.http.routers.docker_registry.service=docker_registry"

        - "traefik.http.services.docker_registry.loadbalancer.server.port=5000"
        - "traefik.http.services.docker_registry.loadbalancer.server.scheme=http"
    image: registry:2.8.3
    configs:
      - source: docker_registry_conf
        target: /etc/docker/registry/config.yml
        mode: 0664
    volumes:
      - type: bind
        source: /buildteam/docker/registry
        target: /var/lib/registry
    networks:
      traefik_reverse-proxy:

  registry-cleanup:
    deploy:
      placement:
        constraints:
          - node.labels.role==infrastructure
      replicas: 0
      restart_policy:
        condition: none
    image: registry:2.8.3
    entrypoint:
      - /entrypoint.sh
      - garbage-collect
      - /etc/docker/registry/config.yml
    configs:
      - source: docker_registry_conf
        target: /etc/docker/registry/config.yml
        mode: 0664
    volumes:
      - type: bind
        source: /buildteam/docker/registry
        target: /var/lib/registry

  frontend:
    deploy:
      placement:
        constraints:
          - node.labels.role==infrastructure
      replicas: 1
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8010:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: build-docker.couchbase.com
      ENV_DOCKER_REGISTRY_PORT: 443
      ENV_DOCKER_REGISTRY_USE_SSL: 1
      ENV_REGISTRY_PROXY_FQDN: build-docker.couchbase.com
      ENV_REGISTRY_PROXY_PORT: 443

  joxit:
    deploy:
      placement:
        constraints:
          - node.labels.role==infrastructure
      replicas: 1
    image: joxit/docker-registry-ui:static
    ports:
      - 8020:80
    environment:
      REGISTRY_URL: https://build-docker.couchbase.com:443
      DELETE_IMAGES: "true"
      REGISTRY_TITLE: "Couchbase Build Registry"

configs:
  docker_registry_conf:
    file: conf/registry-config.yml

networks:
  traefik_reverse-proxy:
    external: true