- name: Check if installed (openjdk)
  stat:
    path: "/usr/local/openjdk-{{ openjdk_version }}"
  register: openjdk

- name: Install jdk
  shell: |
    export PATH=/Users/couchbase/.local/bin:$PATH
    cbdep install openjdk {{ openjdk_version }} -d /usr/local
    rm -f /usr/local/bin/java
    rm -f /usr/local/bin/javac
    ln -s /usr/local/openjdk-{{ openjdk_version }}/bin/java /usr/local/bin/java
    ln -s /usr/local/openjdk-{{ openjdk_version }}/bin/javac /usr/local/bin/javac
  become: true
  when: openjdk.stat.exists == False
