version: "3.8"

# Stack for general-purpose agent capable of running "docker buildx build".

services:
  buildx:
    # Historically, this was the agent used for
    # couchbase-k8s-microservice builds, so it still has
    # operator-specific Jenkins labels.
    image: couchbasebuild/buildx:20250827
    user: couchbase
    environment:
      - "JENKINS_SLAVE_NAME=buildx"
      - "JENKINS_SLAVE_LABELS=couchbase-k8s-microservices couchbase-operator master buildx"
      - "JENKINS_MASTER=http://server.jenkins.couchbase.com/"
      - "NODE_CLASS=build buildx"
      - "NODE_PRODUCT=couchbase-server"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
      - "latestbuilds:/latestbuilds"
      - "releases:/releases"
      - "buildteam:/buildteam"
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
    secrets:
      - source: server_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
      - source: profiledata.ssh_privkey.profile_sync.20200423
        target: /run/secrets/profile_sync
      - source: buildx.config.rhcc_metadata.20240425
        target: /home/couchbase/.docker/rhcc-metadata.json
        mode: 0600
        uid: "1000"
        gid: "1000"
    deploy:
      placement:
        constraints:
          - node.labels.role==docker-buildx
      replicas: 2
      update_config:
        parallelism: 1000

configs:
  jenkins_master_username:
    file: config/jenkins_master_username

secrets:
  server_jenkins_ns-buildbot_api_key.20220510:
    external: true
  buildx.config.rhcc_metadata.20240425:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true

volumes:
  latestbuilds:
    driver: local
    driver_opts:
        type: "nfs"
        o: "addr=cnt-s231.sc.couchbase.com"
        device: ":/data/builds/latestbuilds"

  releases:
    driver: local
    driver_opts:
        type: "nfs"
        o: "addr=cnt-s231.sc.couchbase.com"
        device: ":/data/builds/releases"

  buildteam:
    driver: local
    driver_opts:
        type: "nfs"
        o: "addr=cnt-s231.sc.couchbase.com"
        device: ":/data/buildteam"
