version: '3.8'

# Suggested deployment command:
#   docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c traefik.yaml traefik
# All services, networks, etc. will then get an "traefik_" prefix,
# eg. "traefik_traefik"

services:
  traefik:
    image: traefik:v2.3.7
    secrets:
      - source: wildcard_build_couchbase_com_cert
        target: /certs/wildcard.build.couchbase.com.crt
      - source: wildcard_build_couchbase_com_key
        target: /certs/wildcard.build.couchbase.com.key
      - source: wildcard_couchbase_com_cert
        target: /certs/wildcard.couchbase.com.crt
      - source: wildcard_couchbase_com_key
        target: /certs/wildcard.couchbase.com.key
    configs:
      - source: traefik_config
        target: /etc/traefik/conf.yml
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.watch=true"

      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--api.insecure=true"
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 6725:8080
    deploy:
      replicas: 3
      update_config:
        parallelism: 100
        delay: 0s
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    driver: overlay
    attachable: true

secrets:
  wildcard_build_couchbase_com_cert:
    external: true
    name: wildcard_build_couchbase_com_cert_20240604
  wildcard_build_couchbase_com_key:
    external: true
    name: wildcard_build_couchbase_com_key_20240604
  wildcard_couchbase_com_cert:
    external: true
    name: wildcard_couchbase_com_cert_20250407
  wildcard_couchbase_com_key:
    external: true
    name: wildcard_couchbase_com_key_20250407

configs:
  traefik_config:
    file: traefik-config.yaml
