version: '3.5'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c sdk-jenkins.yaml sdk
# All services, networks, etc. will then get an "sdk_" prefix,
# eg. "sdk_jenkins"

services:

  # sdk.jenkins.couchbase.com
  jenkins:
    image: jenkins/jenkins:2.462.3
    deploy:
      resources:
        limits:
          memory: 7G
        reservations:
          memory: 7G
      placement:
        constraints:
          - node.labels.role==megajenkins
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_reverse-proxy"
        - "traefik.http.routers.sdk_jenkins.rule=Host(`sdk.jenkins.couchbase.com`)"
        - "traefik.http.services.sdk_jenkins.loadbalancer.server.port=8080"
    ports:
      - "50004:50004"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /home/couchbase/sdk-jenkins-home
        target: /var/jenkins_home
    networks:
      - jenkins
      - traefik_reverse-proxy

# See http://www.technowise.in/2016/10/fix-no-valid-crumb-was-included-in.html
# and https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Nginx
# for the reason behind -Dhudson.security.csrf.requestfield
    environment:
      - "JAVA_OPTS=-Dhudson.security.csrf.requestfield=Jenkins-Crumb"
      - "JENKINS_OPTS=--sessionTimeout=1440 --sessionEviction=14400"

networks:
  jenkins:
  traefik_reverse-proxy:
    external: true
